## 错误

`error`

是逻辑的一部分，不会终止程序逻辑运行

程序遇到错误不处理，那么可能进一步的产生业务上的错误，进一步产生了异常

### errors are just values

1. Sentinel errors  哨兵错误

   `io.EOF` 就是提起预定义的错误类型

   ```golang
   func main() {
   	r := bytes.NewReader([]byte("0123456789"))
   	
   	_, err := r.Read(make([]byte, 10))
   	if err == io.EOF {
   		log.Fatal("read failed:", err)
   	}
   }
   ```

   `err.Error()` 方法是给程序员而非代码设计的，也就是说，当我们调用 `Error` 方法时，结果要写到文件或是打印出来，是给程序员看的。在代码里，我们不能根据 `err.Error()` 来做一些判断。

   `Sentinel errors` 最大的问题在于它在定义 error 和使用 error 的包之间建立了依赖关系。比如要想判断 `err == io.EOF` 就得引入 `io` 包，当然这是标准库的包，还行。如果很多用户自定义的包都定义了错误，就要引入很多包来判断各种错误，容易引起循环引用的问题。

2. Error Types 

   指的是实现了 `error` 接口的那些类型。类型中除了 error 外，还可以附带其他字段，从而提供额外的信息，例如出错的行数等。

   ```go
   func underlyingError(err error) error {
   	switch err := err.(type) {
   	case *PathError:
   		return err.Err
   	case *LinkError:
   		return err.Err
   	case *SyscallError:
   		return err.Err
   	}
   	return err
   }
   ```

   在定义错误和使用错误的包之间形成依赖关系。

   即使 `Error types` 比 `Sentinel errors` 好一些，因为它能承载更多的上下文信息，但是它仍然存在引入包依赖的问题。

3. Opaque errors

   “黑盒 errors”，能知道错误发生了，但是不能看到它内部到底是什么。

   ```go
   func fn() error {
   	x, err := bar.Foo()
   	if err != nil {
   		return err
   	}
   
   	return nil
   }
   ```



### github.com/pkg/errors

1. `WithMessage`: 仅增加上下文文本信息，不附加调用栈
2. `WithStack`: 仅增加调用栈
3. `Wrap`:  增加上下文文本信息并附加调用栈
4. `Cause`: 判断底层错误

```go
import (
   "database/sql"
   "fmt"

   "github.com/pkg/errors"
)

func foo() error {
   return errors.Wrap(sql.ErrNoRows, "foo failed")
}

func bar() error {
   return errors.WithMessage(foo(), "bar failed")
}

func main() {
   err := bar()
   if errors.Cause(err) == sql.ErrNoRows {
      fmt.Printf("data not found, %v\n", err)
      fmt.Printf("%+v\n", err)
      return
   }
   if err != nil {
      // unknown error
   }
}
```



### 总结

1. errors 就像对外提供的 API 一样，需要认真对待。

2. 将 errors 看成黑盒，判断它的行为，而不是类型。

3. 尽量不要使用 sentinel errors。

4. 使用第三方的错误包来包裹 error（errors.Wrap），使得它更好用。

5. 使用 errors.Cause 来获取底层的错误。

   

## 异常

`panic`

不应该出现在业务逻辑中，会终止程序逻辑

如果程序遇到异常不处理，那么结果就是进程异常退出

在Go语言项目中，Goroutine如果panic了，并且没有recover，那么整个Go进程就会异常退出。



## 总结

1. 错误和异常需要分类和管理，不能一概而论
2. 错误和异常的分类可以以是否终止业务过程作为标准
3. 错误是业务过程的一部分，异常不是
4. 不要随便捕获异常，更不要随便捕获再重新抛出异常
5. Go语言项目需要把Goroutine分为两类，区别处理异常
6. 在捕获到异常时，需要尽可能的保留第一现场的关键数据